apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vfobs.fullname" . }}
  labels:
    {{- include "vfobs.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "vfobs.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "vfobs.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "vfobs.fullname" . }}
      {{- end }}
      containers:
        - name: vfobs
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: VFOBS_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.dsnSecret.name }}
                  key:  {{ .Values.database.dsnSecret.key }}
            - name: VFOBS_INGEST_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.ingestToken.secret.name }}
                  key:  {{ .Values.ingestToken.secret.key }}
            {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
