{{- if .Values.eso.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "vfobs.fullname" . }}
  labels:
    {{- include "vfobs.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.eso.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.eso.secretStore.name }}
    kind: SecretStore
  target:
    name: {{ .Values.database.dsnSecret.name }}
  data:
    - secretKey: {{ .Values.database.dsnSecret.key }}
      remoteRef:
        key: vfobs/database-url
    - secretKey: {{ .Values.ingestToken.secret.key }}
      remoteRef:
        key: vfobs/ingest-token
{{- end }}
